package app.onlysans.android.ui.theme

import androidx.compose.ui.graphics.Color

// A Material 3 tonal palette built around the azure the joke is borrowed from. Only ever seen when
// dynamic color is switched off, or on a device too old to offer it.
val md_theme_light_primary = Color(0xFF00629E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCFE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D33)
val md_theme_light_secondary = Color(0xFF51606F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4E4F6)
val md_theme_light_onSecondaryContainer = Color(0xFF0D1D2A)
val md_theme_light_tertiary = Color(0xFF68587A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEEDBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF231533)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
val md_theme_light_inversePrimary = Color(0xFF99CBFF)
val md_theme_light_surfaceTint = Color(0xFF00629E)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF99CBFF)
val md_theme_dark_onPrimary = Color(0xFF003355)
val md_theme_dark_primaryContainer = Color(0xFF004A78)
val md_theme_dark_onPrimaryContainer = Color(0xFFCFE5FF)
val md_theme_dark_secondary = Color(0xFFB8C8DA)
val md_theme_dark_onSecondary = Color(0xFF23323F)
val md_theme_dark_secondaryContainer = Color(0xFF394856)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4E4F6)
val md_theme_dark_tertiary = Color(0xFFD3BEE6)
val md_theme_dark_onTertiary = Color(0xFF382A49)
val md_theme_dark_tertiaryContainer = Color(0xFF4F3E61)
val md_theme_dark_onTertiaryContainer = Color(0xFFEEDBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9199)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inversePrimary = Color(0xFF00629E)
val md_theme_dark_surfaceTint = Color(0xFF99CBFF)
val md_theme_dark_scrim = Color(0xFF000000)